# Site settings
title: Mineo Games
email: contact@mineogames.com
url: http://www.mineogames.com
description: Bienvenue sur le site officiel de Mineo Games. Venez d√©couvrir nos jeux ici !
keywords: Mineo Games, Mineo, mineo games, unwelcome, Unwelcome, mineogames, louspirit, officiel, site internet, site

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Mineo Games

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:

pages_list:
  About: 'about'
  Blog: 'last-blog-post'
  Download: 'download'
  Contact: 'contact'

last_post_words: 100

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap